### ISSUE TITLE
NPM warns on using node-uuid

### ISSUE THREAD

**Issue by leondmello** [thaume/ember-cli-uuid#10]
I see this when I ran an install,
```
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
```

**Comment by thaume** [comment]
Hey @leondmello that's a good catch, wanna submit a PR ? :)

**Comment by leondmello** [comment]
@thaume sure

**Comment by leondmello** [comment]
Also, I noticed uuid is up to version `3.0.1`

**Comment by thaume** [comment]
Yes it went from `1.4.7` straight to `3.0.0` 20 days ago :)

We can also upgrade to this version in the same PR. Ping me if you need any kind of help !

**Comment by thaume** [comment]
@leondmello I just did a couple of checks and the transition to `3.0.0` is trickier than expected. The new package is only available as commonjs module or via a CDN. I'll need to look at it again later.

I did revert to 1.4.6 (the version previous to the npm warning that you talked about).

**Comment by thaume** [comment]
I actually took the time this weekend to make the update to `uuid` version `^0.3.1`.

You can find the diff on this pull request : https://github.com/thaume/ember-cli-uuid/pull/13
