### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by rwwagner90** [thaume/ember-cli-uuid#11]
We're using this in our app, but there are lots of things that need to be updated. Is anyone maintaining this? If not, and you would be willing to transfer ownership to my org, we'd be happy to get it updated to all the latest ember standards! Please let me know your thoughts.

**Comment by thaume** [comment]
Hey there,

Yes I'm using it in my apps too and it works well. I haven't finished the migration to the latest uuid.js package and as you said the way the code is written is not sync with the latest Ember standard.

I would gladly accept a PR and work on it with you if you want to invest some time into it.

**Comment by rwwagner90** [comment]
@thaume it will require a lot of updates. It would likely be just as quick to create a new addon that uses all the latest stuff. With that in mind, I would probably be more inclined to just make a new one, to add to the Ship Shape addons. I'll have to take a peek at the code and see what would be easier.

**Comment by thaume** [comment]
All right best of luck then :)

**Comment by rwwagner90** [comment]
@thaume it looks like you went ahead and did all the updating, thanks! I think the only suggestion I would have now, is to use ember-cli-node-assets to pull down the npm package, instead of using a blueprint to add it to the consuming project. What are your thoughts on that? I'd be happy to implement it.

**Comment by thaume** [comment]
@rwwagner90 yeah I guess you reminded me that this project needed updates :P

I was actually discussing it on the ember slack a couple of days ago, I don't really have an opinion on the matter. If you think this is a more idiomatic way of doing it, let's do it !

**Comment by rwwagner90** [comment]
@thaume I think it's really nice to be able to just `ember install ember-cli-uuid` and have only `ember-cli-uuid` show up in package.json and everything just works. If you agree, I can definitely PR this in 😄

**Comment by thaume** [comment]
@rwwagner90 alright sounds good to me, we can then publish 0.5.0 once this is merged !

**Comment by thaume** [comment]
Let's merge the PR first ?

**Comment by rwwagner90** [comment]
@thaume the reason I was asking, is so I can just branch off the actual repo, rather than forking. Just makes things easier.

**Comment by thaume** [comment]
Alright, I'll add you now
