### ISSUE TITLE
node-uuid missing

### ISSUE THREAD

**Issue by AnshuAg** [thaume/ember-cli-uuid#12]
We installed 'ember-cli-uuid' package via ember install. It installed only 2 packages i.e ember-cli-uuid and uuid . 

But when we try to run the application we got the error : -
Cannot find module 'node-uuid/package.json'

Can someone help us out?  We are pretty new to ember.js.

**Comment by thaume** [comment]
Snap, I'll look into that right now, can you try to install the previous version ? 0.4.1 ?

I'll push an update in a couple of minutes

**Comment by thaume** [comment]
@anshuag alright I pushed an up to date version, please run ember install ember-cli-uuid again and the error should be gone.

If you want help regarding ember, join us on the slack :) it is over here : https://ember-community-slackin.herokuapp.com, you can reach me there via : @thaume. Let me know how that goes

**Comment by AnshuAg** [comment]
Thanks @thaume for fixing it this quick :)

**Comment by thaume** [comment]
@AnshuAg my pleasure ! Let me know if you need anything else
