### ISSUE TITLE
Documentation incorrect or misleading.

### ISSUE THREAD

**Issue by hvgotcodes** [thaume/ember-cli-uuid#17]
The documentation talks about a mixin but there appears to be no mixin.  Trying the import

`import AdaptersUuidMixin from 'ember-cli-uuid/mixins/adapters/uuid';`

the interpreter can't find the import.  Also, I don't see the mixin in the node module.

**Comment by thaume** [comment]
Hello there !

Are you using the latest version of the module (0.6.0) ?

**Comment by hvgotcodes** [comment]
Ah, that's my bad, sorry!  

Should the 0.5 version create UUIDs for models in tests if we did not use the configuration option to turn off auto-generation?

**Comment by thaume** [comment]
No worries !

We implemented the mixin to be able to generate uuids in tests (in 0.6.0) :)
