### ISSUE TITLE
Why is ember-cli-update a dependency, rather than devDependency?

### ISSUE THREAD

**Issue by foxtree** [thaume/ember-cli-uuid#20]
It seems that in `package.json`, `ember-cli-update` is listed under `dependencies`, rather than `devDependencies`.

Why is this necessary?

...This has a variety adverse consequences.   

My understanding is that the default behavior of `npm install` and `yarn install` is that `devDependencies` and transitive `devDependencies` are not supposed to be installed.

I currently have a situation where a deeply-nested, transitive `devDependencies` of `ember-cli-update` is incompatible with a remote system I am dealing with, and over which I have little control.

**Comment by thaume** [comment]
Hi @foxtree 

You are absolutely right, that is a mistake on my side.

I'll cut an update right away

**Comment by thaume** [comment]
https://github.com/thaume/ember-cli-uuid/releases/tag/v0.14.1 + pushed to NPM

Let me know how that goes

**Comment by foxtree** [comment]
Yes, this does work -- thank you so much!

**Comment by thaume** [comment]
My pleasure :)
