### ISSUE TITLE
Use an empty ID flag? 

### ISSUE THREAD

**Issue by ryanlitalien** [thaume/ember-cli-uuid#8]
Hi @thaume,
Do you have a flag that i can pass on `store.createRecord` that I can skip ID generation? Since I'm saving to Rails, I have to clear out the ID field before the initial save.

```javascript
bicycle.set('id', null);
bicycle.save()...
```

**Comment by thaume** [comment]
Hi @ryanlitalien,
What is the purpose of creating an empty ID in your use-case ? This module was specifically created to generate IDs on the client-side.
Do you need to generate UUIDs outside of the Ember-Data record ? (or in another field than the primary key) ?

**Comment by huberts** [comment]
Hello, @thaume !
I think it could be a nice feature. E. g. I wish to use UUIDs for volatile objects (complex queries, not having direct representation in DB) when I need to track them with some unique identifier. But still, I wish to **create** real objects persisted in DB, which won't get their UUIDs at client side but rather on server side.
Note that you cannot do both on Ember - If an object has already an UUIDed (fake) id, then you cannot overwrite it with a DB entry id.

**Comment by thaume** [comment]
Hello @huberts !
This module was first created to manage UUIDs 100% client side. Meaning that Rails doesn't get to create your records IDs.
This module could be called "UUIDs first" as opposed to what you want that we could call "UUIDs sometimes".
This is still an interesting need :) Here is what I propose for the API :

### I want 100% client-side UUIDs
No changes, you just need to `ember install ember-cli-uuid` and **all** your records will receive a v4 UUID (that will have to be, like you said, persisted server-side).

### I want to use UUIDs for some models
We could manage that in the config file :

```javascript
const ENV = {
  // ... others config vars
  'ember-cli-uuid': {
    autoUUID: false
  }
};
```

This way, you could use UUIDs as primary key only when you need them :

```javascript
import {uuid} from 'ember-cli-uuid';

bicycle.set('id', uuid());
bicycle.save();
```

What do you guys think ?

cc @ryanlitalien

**Comment by huberts** [comment]
Hello!

It looks great for me. Serves my usage pattern and is pretty straightforward. Thank you!

**Comment by thaume** [comment]
Awesome, I'll try to work on it this week !

If you have anything to add @ryanlitalien, I'll keep the issue open

**Comment by thaume** [comment]
Hey guys,

I had a some time during my lunch break, so I gave the new `defaultUUID` **config var** a shot. Here is the commit : https://github.com/thaume/ember-cli-uuid/commit/d5ffc3f51903115bf4452b72d63cdb1b91800c0f

If you want to try it on your project, you just need to install the master branch (instead of the npm package).

And then, in your `config/environment.js` file, you need to add :
````javascript
const ENV = {
  // ... others config vars
  'ember-cli-uuid': {
    autoUUID: false
  }
};
```

This should stop the package from generating UUID for your records.

Let me know how that goes !

**Comment by ryanlitalien** [comment]
Hey @thaume, this worked well, thanks!

Although the `ENV` declaration was a bit off.

I had to add `defaultUUID` (instead of `autoUUID`) to the main `ENV` props:
```
var ENV = {
  defaultUUID: false,
  ...
}
```
As you reference it off the base `ENV` hash and it ignores the `'ember-cli-uuid'` subkey.

https://github.com/thaume/ember-cli-uuid/commit/d5ffc3f51903115bf4452b72d63cdb1b91800c0f#diff-c77931e5345bac635863cd91f8e40268R14

**Comment by thaume** [comment]
Alright, I'll clean it up before tagging a release. It would be better to namespace inside 'ember-cli-uudi'.

**Comment by thaume** [comment]
@ryanlitalien @huberts here we are : 
https://github.com/thaume/ember-cli-uuid/releases/tag/v0.4.0
https://www.npmjs.com/package/ember-cli-uuid

Let me know if anything goes wrong :)
